server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:5001/;
    }

    location /products/ {
        proxy_pass http://product-service:5002/;
    }

    location /orders/ {
        proxy_pass http://order-service:5003/;
    }

    location / {
        return 200 "E-commerce API Gateway\n";
    }
}

